### ISSUE TITLE
add UI components

### ISSUE THREAD

**Issue by jbesraa** [berkeley-homes/near-miss-positive-intervention#23]
- [ ] Logo
- [ ] Welcome Message
- [ ] Landing Page
- [ ] Positive Button
- [ ] Negative Button
- [ ] Name input field
- [ ] Three location dropdown menu
- [ ] Upload Image
- [ ] Message input field
- [ ] send button 
- [ ] Thank you Message

**Comment by jbesraa** [comment]
@des-des did I miss something ?

**Comment by des-des** [comment]
done
