### ISSUE TITLE
Shorthand Names for the Location options

### ISSUE THREAD

**Issue by sohilpandya** [berkeley-homes/near-miss-positive-intervention#34]
Hi @Brian-GF & @Ben-BHNEL,

Hope you are doing well, we've got a question with regards to the location document that was sent to us. In its current form, the items will look like the following when the user selects the drop-down
**NE Block, Core 11, Level 11**

Is that how we'd like to keep the naming or would we like to abbreviate these so that instead of the above we show the following:
**NE, C 11, L 11**

Which one would you like to show to the users when they are selecting the locations?

**Comment by Ben-BHNEL** [comment]
@sohilpandya Brian and I are both in agreement that we would like the location to be set out with **NE Block, Core 11, Level 11.**

**Comment by sohilpandya** [comment]
@Ben-BHNEL thanks for the prompt response! 👍

**Comment by des-des** [comment]
Yay just pushed up the code for this
