### ISSUE TITLE
Upload page: add dropdown svg's

### ISSUE THREAD

**Issue by nogainbar** [berkeley-homes/near-miss-positive-intervention#47]
to dropdown input fields
and
- style drop down menus

**Comment by nogainbar** [comment]
@des-des is there a reason why you build the dropdown component with <select>? there is no way to style the dropdown list that comes down from a <select> apparently.. would it be possible to do so it as a `ul`'s and `li`'s?

**Comment by des-des** [comment]
@nogainbar look at it on your mobile, might be very fiddly / hard to recreate native dropdown. We can get a third party one?

**Comment by nogainbar** [comment]
@des-des thats cool! no worries about it
